# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-18 03:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('board', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='GameAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.IntegerField()),
                ('y', models.IntegerField()),
                ('action_type', models.IntegerField(choices=[(0, 'CLICK'), (1, 'FLAG')])),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='miner.Game')),
            ],
        ),
    ]
