# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-19 18:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='state',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gameaction',
            name='action_type',
            field=models.IntegerField(choices=[(0, 'CLICK'), (1, 'DOUBLE_CLICK'), (2, 'FLAG')]),
        ),
    ]
